# Generated by Django 3.1.5 on 2021-03-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_complaintfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='meetingp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('tname', models.CharField(max_length=50)),
                ('aud', models.CharField(max_length=50)),
                ('tnd', models.CharField(max_length=50)),
                ('agenda', models.TextField()),
            ],
        ),
    ]
