# Generated by Django 3.1.5 on 2021-03-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_meetingp'),
    ]

    operations = [
        migrations.CreateModel(
            name='mreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('tname', models.CharField(max_length=50)),
                ('mon', models.CharField(max_length=15)),
                ('report', models.TextField()),
            ],
        ),
    ]
